name: 'Product Adverts'
type: module
description: 'My Awesome Module'
core_version_requirement: '^9.3 || ^10'
package: Custom
dependencies:
  - commerce:commerce_product
  - product_adverts:product_adverts
  - drupal:rest
  - drupal:serialization
  - drupal:views
  - adverts:adverts
