name: 'Product Adverts'
type: module
description: 'My Awesome Module'
core_version_requirement: '^8.9 || ^9'
package: Custom
dependencies:
  - commerce_product
  - product_adverts
  - rest
  - serialization
  - views
  - adverts
